# ios/Podfile

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# Flutter Podfile generated. Don't manually edit this.
# To add dependencies to your Flutter project, add them to the pubspec.yaml
# in the root of your Flutter project.
#
# For information on how to write a Podfile, see
# https://guides.cocoapods.org/syntax/podfile.html
#

platform :ios, '15.5'
