# ios/Podfile

# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# Flutter Podfile generated. Don't manually edit this.
# To add dependencies to your Flutter project, add them to the pubspec.yaml
# in the root of your Flutter project.
#
# For information on how to write a Podfile, see
# https://guides.cocoapods.org/syntax/podfile.html
#

platform :ios, '15.5'

# 省略... (Podfileの残りの部分はそのまま)

flutter_application_path = '../..'
load File.join(flutter_application_path, '.ios', 'Flutter', 'podhelper.rb')

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_pods_debug_config(flutter_application_path)

  target 'RunnerTests' do
    inherit! :search_paths
  end
end
